// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Authenticate {
    #[prost(uint32, tag = "1")]
    pub msg_id: u32,
    #[prost(uint64, tag = "2")]
    pub msg_date: u64,
    #[prost(string, tag = "3")]
    pub jwt: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Subscribe {
    #[prost(uint32, tag = "1")]
    pub msg_id: u32,
    #[prost(uint64, tag = "2")]
    pub msg_date: u64,
    #[prost(uint32, tag = "3")]
    pub proto: u32,
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub channels: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Unsubscribe {
    #[prost(uint32, tag = "1")]
    pub msg_id: u32,
    #[prost(uint64, tag = "2")]
    pub msg_date: u64,
    #[prost(uint32, tag = "3")]
    pub proto: u32,
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub channels: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Payload {
    #[prost(uint32, tag = "1")]
    pub msg_id: u32,
    #[prost(uint64, tag = "2")]
    pub msg_date: u64,
    #[prost(uint32, optional, tag = "3")]
    pub proto: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub src: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", repeated, tag = "5")]
    pub dests: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "7")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Disconnect {
    #[prost(uint32, tag = "1")]
    pub msg_id: u32,
    #[prost(uint64, tag = "2")]
    pub msg_date: u64,
    #[prost(bool, tag = "3")]
    pub reconnect: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    Unspecified = 0,
    Authenticate = 1,
    Subscribe = 2,
    Unsubscribe = 3,
    Payload = 6,
    Error = 9,
    Disconnect = 10,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MESSAGE_TYPE_UNSPECIFIED",
            Self::Authenticate => "AUTHENTICATE",
            Self::Subscribe => "SUBSCRIBE",
            Self::Unsubscribe => "UNSUBSCRIBE",
            Self::Payload => "PAYLOAD",
            Self::Error => "ERROR",
            Self::Disconnect => "DISCONNECT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MESSAGE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "AUTHENTICATE" => Some(Self::Authenticate),
            "SUBSCRIBE" => Some(Self::Subscribe),
            "UNSUBSCRIBE" => Some(Self::Unsubscribe),
            "PAYLOAD" => Some(Self::Payload),
            "ERROR" => Some(Self::Error),
            "DISCONNECT" => Some(Self::Disconnect),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Proto {
    Unknown = 0,
    Qconnect = 1,
}
impl Proto {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "PROTO_UNKNOWN",
            Self::Qconnect => "PROTO_QCONNECT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROTO_UNKNOWN" => Some(Self::Unknown),
            "PROTO_QCONNECT" => Some(Self::Qconnect),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChannelType {
    Unspecified = 0,
    Device = 1,
    Backend = 2,
    SessionControllers = 3,
}
impl ChannelType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CHANNEL_TYPE_UNSPECIFIED",
            Self::Device => "CHANNEL_TYPE_DEVICE",
            Self::Backend => "CHANNEL_TYPE_BACKEND",
            Self::SessionControllers => "CHANNEL_TYPE_SESSION_CONTROLLERS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHANNEL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CHANNEL_TYPE_DEVICE" => Some(Self::Device),
            "CHANNEL_TYPE_BACKEND" => Some(Self::Backend),
            "CHANNEL_TYPE_SESSION_CONTROLLERS" => Some(Self::SessionControllers),
            _ => None,
        }
    }
}
