// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlaybackError {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(int32, tag = "2")]
    pub queue_item_id: i32,
    #[prost(enumeration = "ErrorType", tag = "3")]
    pub error_type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticateMessage {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceCapabilities {
    #[prost(enumeration = "AudioQuality", tag = "1")]
    pub min_audio_quality: i32,
    #[prost(enumeration = "AudioQuality", tag = "2")]
    pub max_audio_quality: i32,
    #[prost(enumeration = "VolumeRemoteControl", tag = "3")]
    pub volume_remote_control: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceInfo {
    #[prost(bytes = "vec", tag = "1")]
    pub device_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub friendly_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub brand: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub serial_number: ::prost::alloc::string::String,
    #[prost(enumeration = "DeviceType", tag = "6")]
    pub r#type: i32,
    #[prost(message, optional, tag = "7")]
    pub capabilities: ::core::option::Option<DeviceCapabilities>,
    #[prost(string, tag = "8")]
    pub software_version: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Position {
    #[prost(fixed64, tag = "1")]
    pub timestamp: u64,
    #[prost(uint32, tag = "2")]
    pub value: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueueVersion {
    #[prost(uint32, tag = "1")]
    pub major: u32,
    #[prost(uint32, tag = "2")]
    pub minor: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueueTrack {
    #[prost(int32, tag = "1")]
    pub queue_item_id: i32,
    #[prost(fixed32, tag = "2")]
    pub track_id: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueueTrackRef {
    #[prost(int32, tag = "1")]
    pub queue_item_id: i32,
    #[prost(fixed32, tag = "2")]
    pub track_id: u32,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub context_uuid: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrJoinSession {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub session_uuid: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "2")]
    pub device_info: ::core::option::Option<DeviceInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrSetPlayerState {
    #[prost(enumeration = "PlayingState", optional, tag = "1")]
    pub playing_state: ::core::option::Option<i32>,
    #[prost(uint32, optional, tag = "2")]
    pub current_position: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "3")]
    pub current_queue_item: ::core::option::Option<QueueItemRef>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueueItemRef {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(int32, tag = "2")]
    pub id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrSetActiveRenderer {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrSetVolume {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
    #[prost(uint32, optional, tag = "2")]
    pub volume: ::core::option::Option<u32>,
    #[prost(int32, optional, tag = "3")]
    pub volume_delta: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrMuteVolume {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
    #[prost(bool, tag = "2")]
    pub value: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrSetLoopMode {
    #[prost(enumeration = "LoopMode", tag = "1")]
    pub loop_mode: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrSetAutoplayMode {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "3")]
    pub autoplay_mode: bool,
    #[prost(bool, tag = "4")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "5")]
    pub autoplay_loading: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrSetMaxAudioQuality {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
    #[prost(enumeration = "AudioQuality", tag = "2")]
    pub max_audio_quality: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlMaxAudioQualityChanged {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
    #[prost(enumeration = "AudioQuality", tag = "2")]
    pub max_audio_quality: i32,
    #[prost(enumeration = "NetworkType", optional, tag = "3")]
    pub network_type: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlFileAudioQualityChanged {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
    #[prost(uint32, tag = "2")]
    pub sampling_rate: u32,
    #[prost(uint32, tag = "3")]
    pub bit_depth: u32,
    #[prost(uint32, tag = "4")]
    pub nb_channels: u32,
    #[prost(enumeration = "AudioQuality", tag = "5")]
    pub audio_quality: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlDeviceAudioQualityChanged {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
    #[prost(uint32, tag = "2")]
    pub sampling_rate: u32,
    #[prost(uint32, tag = "3")]
    pub bit_depth: u32,
    #[prost(uint32, tag = "4")]
    pub nb_channels: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrAskForRendererState {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrAskForQueueState {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtrlSrvrSetQueueState {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "3")]
    pub tracks: ::prost::alloc::vec::Vec<TrackRef>,
    #[prost(bool, tag = "4")]
    pub shuffle_mode: bool,
    #[prost(uint32, repeated, tag = "5")]
    pub shuffled_track_indexes: ::prost::alloc::vec::Vec<u32>,
    #[prost(bool, tag = "6")]
    pub autoplay_mode: bool,
    #[prost(bool, tag = "7")]
    pub autoplay_loading: bool,
    #[prost(message, repeated, tag = "8")]
    pub autoplay_tracks: ::prost::alloc::vec::Vec<TrackRef>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrackRef {
    #[prost(fixed32, tag = "1")]
    pub track_id: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub context_uuid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrClearQueue {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrQueueLoadTracks {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(fixed32, repeated, tag = "3")]
    pub track_ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "4")]
    pub queue_position: u32,
    #[prost(fixed32, optional, tag = "5")]
    pub shuffle_seed: ::core::option::Option<u32>,
    #[prost(int32, optional, tag = "6")]
    pub shuffle_pivot_index: ::core::option::Option<i32>,
    #[prost(bool, optional, tag = "7")]
    pub shuffle_mode: ::core::option::Option<bool>,
    #[prost(bytes = "vec", tag = "8")]
    pub context_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "9")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "10")]
    pub autoplay_loading: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrQueueInsertTracks {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(fixed32, repeated, tag = "3")]
    pub track_ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(int32, optional, tag = "4")]
    pub insert_after: ::core::option::Option<i32>,
    #[prost(fixed32, optional, tag = "5")]
    pub shuffle_seed: ::core::option::Option<u32>,
    #[prost(bytes = "vec", tag = "6")]
    pub context_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "7")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "8")]
    pub autoplay_loading: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrQueueAddTracks {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(fixed32, repeated, tag = "3")]
    pub track_ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(fixed32, optional, tag = "4")]
    pub shuffle_seed: ::core::option::Option<u32>,
    #[prost(bytes = "vec", tag = "5")]
    pub context_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "6")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "7")]
    pub autoplay_loading: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrQueueRemoveTracks {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, repeated, tag = "3")]
    pub queue_item_ids: ::prost::alloc::vec::Vec<i32>,
    #[prost(bool, tag = "4")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "5")]
    pub autoplay_loading: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrQueueReorderTracks {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, repeated, tag = "3")]
    pub queue_item_ids: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "4")]
    pub insert_after: ::core::option::Option<i32>,
    #[prost(bool, tag = "5")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "6")]
    pub autoplay_loading: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrSetShuffleMode {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "3")]
    pub shuffle_mode: bool,
    #[prost(fixed32, optional, tag = "4")]
    pub shuffle_seed: ::core::option::Option<u32>,
    #[prost(int32, optional, tag = "5")]
    pub shuffle_pivot_queue_item_id: ::core::option::Option<i32>,
    #[prost(bool, tag = "6")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "7")]
    pub autoplay_loading: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrAutoplayLoadTracks {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(fixed32, repeated, tag = "3")]
    pub track_ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(bytes = "vec", tag = "4")]
    pub context_uuid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CtrlSrvrAutoplayRemoveTracks {
    #[prost(message, optional, tag = "1")]
    pub queue_version_ref: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, repeated, tag = "3")]
    pub queue_item_ids: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlSessionState {
    #[prost(bytes = "vec", tag = "1")]
    pub session_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "2")]
    pub active_renderer_id: i32,
    #[prost(message, optional, tag = "3")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(enumeration = "PlayingState", tag = "4")]
    pub playing_state: i32,
    #[prost(enumeration = "LoopMode", tag = "5")]
    pub loop_mode: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlRendererStateUpdated {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
    #[prost(enumeration = "RendererStatus", tag = "2")]
    pub status: i32,
    #[prost(message, optional, tag = "3")]
    pub player_state: ::core::option::Option<RendererState>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RendererState {
    #[prost(enumeration = "PlayingState", tag = "1")]
    pub playing_state: i32,
    #[prost(enumeration = "BufferState", tag = "2")]
    pub buffer_state: i32,
    #[prost(message, optional, tag = "3")]
    pub current_position: ::core::option::Option<Position>,
    #[prost(uint32, tag = "4")]
    pub duration: u32,
    #[prost(int32, tag = "5")]
    pub current_queue_item_id: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlAddRenderer {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
    #[prost(message, optional, tag = "2")]
    pub device_info: ::core::option::Option<DeviceInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlUpdateRenderer {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
    #[prost(message, optional, tag = "2")]
    pub device_info: ::core::option::Option<DeviceInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlRemoveRenderer {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlActiveRendererChanged {
    #[prost(int32, tag = "1")]
    pub active_renderer_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlVolumeChanged {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
    #[prost(uint32, tag = "2")]
    pub volume: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlVolumeMuted {
    #[prost(int32, tag = "1")]
    pub renderer_id: i32,
    #[prost(bool, tag = "2")]
    pub value: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlLoopModeSet {
    #[prost(enumeration = "LoopMode", tag = "1")]
    pub loop_mode: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SrvrCtrlQueueState {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub action_uuid: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, repeated, tag = "3")]
    pub tracks: ::prost::alloc::vec::Vec<QueueTrackRef>,
    #[prost(bool, tag = "4")]
    pub shuffle_mode: bool,
    #[prost(uint32, repeated, tag = "5")]
    pub shuffled_track_indexes: ::prost::alloc::vec::Vec<u32>,
    #[prost(bool, tag = "6")]
    pub autoplay_mode: bool,
    #[prost(bool, tag = "7")]
    pub autoplay_loading: bool,
    #[prost(message, repeated, tag = "8")]
    pub autoplay_tracks: ::prost::alloc::vec::Vec<QueueTrackRef>,
    #[prost(bytes = "vec", optional, tag = "100")]
    pub queue_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlQueueCleared {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SrvrCtrlQueueTracksLoaded {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "3")]
    pub tracks: ::prost::alloc::vec::Vec<QueueTrack>,
    #[prost(uint32, tag = "4")]
    pub queue_position: u32,
    #[prost(fixed32, optional, tag = "5")]
    pub shuffle_seed: ::core::option::Option<u32>,
    #[prost(int32, optional, tag = "6")]
    pub shuffle_pivot_queue_item_id: ::core::option::Option<i32>,
    #[prost(bool, optional, tag = "7")]
    pub shuffle_mode: ::core::option::Option<bool>,
    #[prost(bytes = "vec", tag = "8")]
    pub context_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "9")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "10")]
    pub autoplay_loading: bool,
    #[prost(bytes = "vec", optional, tag = "100")]
    pub queue_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlQueueTracksReordered {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, repeated, tag = "3")]
    pub queue_item_ids: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "4")]
    pub insert_after: ::core::option::Option<i32>,
    #[prost(bool, tag = "5")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "6")]
    pub autoplay_loading: bool,
    #[prost(bytes = "vec", optional, tag = "100")]
    pub queue_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlQueueTracksRemoved {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, repeated, tag = "3")]
    pub queue_item_ids: ::prost::alloc::vec::Vec<i32>,
    #[prost(bool, tag = "4")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "5")]
    pub autoplay_loading: bool,
    #[prost(bytes = "vec", optional, tag = "100")]
    pub queue_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SrvrCtrlQueueTracksAdded {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "3")]
    pub tracks: ::prost::alloc::vec::Vec<QueueTrack>,
    #[prost(fixed32, optional, tag = "4")]
    pub shuffle_seed: ::core::option::Option<u32>,
    #[prost(bytes = "vec", tag = "5")]
    pub context_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "6")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "7")]
    pub autoplay_loading: bool,
    #[prost(bytes = "vec", optional, tag = "100")]
    pub queue_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlQueueTracksAddedFromAutoplay {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(int32, repeated, tag = "2")]
    pub queue_item_ids: ::prost::alloc::vec::Vec<i32>,
    #[prost(bytes = "vec", optional, tag = "100")]
    pub queue_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SrvrCtrlQueueTracksInserted {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "3")]
    pub tracks: ::prost::alloc::vec::Vec<QueueTrack>,
    #[prost(int32, optional, tag = "4")]
    pub insert_after: ::core::option::Option<i32>,
    #[prost(fixed32, optional, tag = "5")]
    pub shuffle_seed: ::core::option::Option<u32>,
    #[prost(bytes = "vec", tag = "6")]
    pub context_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "7")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "8")]
    pub autoplay_loading: bool,
    #[prost(bytes = "vec", optional, tag = "100")]
    pub queue_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlShuffleModeSet {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "3")]
    pub shuffle_mode: bool,
    #[prost(fixed32, optional, tag = "4")]
    pub shuffle_seed: ::core::option::Option<u32>,
    #[prost(int32, optional, tag = "5")]
    pub shuffle_pivot_queue_item_id: ::core::option::Option<i32>,
    #[prost(bool, tag = "6")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "7")]
    pub autoplay_loading: bool,
    #[prost(bytes = "vec", optional, tag = "100")]
    pub queue_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlAutoplayModeSet {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "3")]
    pub autoplay_mode: bool,
    #[prost(bool, tag = "4")]
    pub autoplay_reset: bool,
    #[prost(bool, tag = "5")]
    pub autoplay_loading: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SrvrCtrlAutoplayTracksLoaded {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "3")]
    pub tracks: ::prost::alloc::vec::Vec<QueueTrack>,
    #[prost(bytes = "vec", tag = "4")]
    pub context_uuid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlAutoplayTracksRemoved {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, repeated, tag = "3")]
    pub queue_item_ids: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrCtrlQueueErrorMessage {
    #[prost(message, optional, tag = "1")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(bytes = "vec", tag = "2")]
    pub action_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub error: ::core::option::Option<Error>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RndrSrvrJoinSession {
    #[prost(bytes = "vec", tag = "1")]
    pub session_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub device_info: ::core::option::Option<DeviceInfo>,
    #[prost(enumeration = "JoinSessionReason", tag = "3")]
    pub reason: i32,
    #[prost(message, optional, tag = "4")]
    pub initial_state: ::core::option::Option<QueueRendererState>,
    #[prost(bool, optional, tag = "5")]
    pub is_active: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RndrSrvrDeviceInfoUpdated {
    #[prost(message, optional, tag = "1")]
    pub device_info: ::core::option::Option<DeviceInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RndrSrvrStateUpdated {
    #[prost(message, optional, tag = "1")]
    pub state: ::core::option::Option<QueueRendererState>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RndrSrvrRendererAction {
    #[prost(uint32, optional, tag = "1")]
    pub seek_position: ::core::option::Option<u32>,
    #[prost(enumeration = "ActionType", tag = "2")]
    pub action: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RndrSrvrVolumeChanged {
    #[prost(uint32, tag = "1")]
    pub volume: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RndrSrvrVolumeMuted {
    #[prost(bool, tag = "1")]
    pub value: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RndrSrvrMaxAudioQualityChanged {
    #[prost(enumeration = "AudioQuality", tag = "1")]
    pub max_audio_quality: i32,
    #[prost(enumeration = "NetworkType", optional, tag = "2")]
    pub network_type: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RndrSrvrFileAudioQualityChanged {
    #[prost(uint32, tag = "1")]
    pub sampling_rate: u32,
    #[prost(uint32, tag = "2")]
    pub bit_depth: u32,
    #[prost(uint32, tag = "3")]
    pub nb_channels: u32,
    #[prost(enumeration = "AudioQuality", tag = "4")]
    pub audio_quality: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RndrSrvrDeviceAudioQualityChanged {
    #[prost(uint32, tag = "1")]
    pub sampling_rate: u32,
    #[prost(uint32, tag = "2")]
    pub bit_depth: u32,
    #[prost(uint32, tag = "3")]
    pub nb_channels: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrRndrSetState {
    #[prost(enumeration = "PlayingState", optional, tag = "1")]
    pub playing_state: ::core::option::Option<i32>,
    #[prost(uint32, optional, tag = "2")]
    pub current_position: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "3")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(message, optional, tag = "4")]
    pub current_track: ::core::option::Option<QueueTrackRef>,
    #[prost(message, optional, tag = "5")]
    pub next_track: ::core::option::Option<QueueTrackRef>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrRndrSetVolume {
    #[prost(uint32, optional, tag = "1")]
    pub volume: ::core::option::Option<u32>,
    #[prost(int32, optional, tag = "2")]
    pub volume_delta: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrRndrMuteVolume {
    #[prost(bool, tag = "1")]
    pub value: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrRndrSetMaxAudioQuality {
    #[prost(enumeration = "AudioQuality", tag = "1")]
    pub max_audio_quality: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrRndrSetLoopMode {
    #[prost(enumeration = "LoopMode", tag = "1")]
    pub loop_mode: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrRndrSetShuffleMode {
    #[prost(bool, tag = "1")]
    pub shuffle_mode: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SrvrRndrSetActive {
    #[prost(bool, tag = "1")]
    pub active: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueueRendererState {
    #[prost(enumeration = "PlayingState", tag = "1")]
    pub playing_state: i32,
    #[prost(enumeration = "BufferState", tag = "2")]
    pub buffer_state: i32,
    #[prost(message, optional, tag = "3")]
    pub current_position: ::core::option::Option<Position>,
    #[prost(uint32, tag = "4")]
    pub duration: u32,
    #[prost(message, optional, tag = "5")]
    pub queue_version: ::core::option::Option<QueueVersion>,
    #[prost(int32, tag = "6")]
    pub current_queue_item_id: i32,
    #[prost(int32, tag = "7")]
    pub next_queue_item_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QConnectBatch {
    #[prost(fixed64, tag = "1")]
    pub messages_time: u64,
    #[prost(int32, tag = "2")]
    pub messages_id: i32,
    #[prost(message, repeated, tag = "3")]
    pub messages: ::prost::alloc::vec::Vec<QConnectMessage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QConnectMessage {
    #[prost(enumeration = "MessageType", tag = "1")]
    pub message_type: i32,
    #[prost(message, optional, tag = "2")]
    pub error: ::core::option::Option<Error>,
    #[prost(message, optional, tag = "3")]
    pub playback_error: ::core::option::Option<PlaybackError>,
    #[prost(message, optional, tag = "4")]
    pub authenticate: ::core::option::Option<AuthenticateMessage>,
    #[prost(message, optional, tag = "21")]
    pub rndr_srvr_join_session: ::core::option::Option<RndrSrvrJoinSession>,
    #[prost(message, optional, tag = "22")]
    pub rndr_srvr_device_info_updated: ::core::option::Option<RndrSrvrDeviceInfoUpdated>,
    #[prost(message, optional, tag = "23")]
    pub rndr_srvr_state_updated: ::core::option::Option<RndrSrvrStateUpdated>,
    #[prost(message, optional, tag = "24")]
    pub rndr_srvr_renderer_action: ::core::option::Option<RndrSrvrRendererAction>,
    #[prost(message, optional, tag = "25")]
    pub rndr_srvr_volume_changed: ::core::option::Option<RndrSrvrVolumeChanged>,
    #[prost(message, optional, tag = "26")]
    pub rndr_srvr_file_audio_quality_changed:
        ::core::option::Option<RndrSrvrFileAudioQualityChanged>,
    #[prost(message, optional, tag = "27")]
    pub rndr_srvr_device_audio_quality_changed:
        ::core::option::Option<RndrSrvrDeviceAudioQualityChanged>,
    #[prost(message, optional, tag = "28")]
    pub rndr_srvr_max_audio_quality_changed: ::core::option::Option<RndrSrvrMaxAudioQualityChanged>,
    #[prost(message, optional, tag = "29")]
    pub rndr_srvr_volume_muted: ::core::option::Option<RndrSrvrVolumeMuted>,
    #[prost(message, optional, tag = "41")]
    pub srvr_rndr_set_state: ::core::option::Option<SrvrRndrSetState>,
    #[prost(message, optional, tag = "42")]
    pub srvr_rndr_set_volume: ::core::option::Option<SrvrRndrSetVolume>,
    #[prost(message, optional, tag = "43")]
    pub srvr_rndr_set_active: ::core::option::Option<SrvrRndrSetActive>,
    #[prost(message, optional, tag = "44")]
    pub srvr_rndr_set_max_audio_quality: ::core::option::Option<SrvrRndrSetMaxAudioQuality>,
    #[prost(message, optional, tag = "45")]
    pub srvr_rndr_set_loop_mode: ::core::option::Option<SrvrRndrSetLoopMode>,
    #[prost(message, optional, tag = "46")]
    pub srvr_rndr_set_shuffle_mode: ::core::option::Option<SrvrRndrSetShuffleMode>,
    #[prost(message, optional, tag = "47")]
    pub srvr_rndr_mute_volume: ::core::option::Option<SrvrRndrMuteVolume>,
    #[prost(message, optional, tag = "61")]
    pub ctrl_srvr_join_session: ::core::option::Option<CtrlSrvrJoinSession>,
    #[prost(message, optional, tag = "62")]
    pub ctrl_srvr_set_player_state: ::core::option::Option<CtrlSrvrSetPlayerState>,
    #[prost(message, optional, tag = "63")]
    pub ctrl_srvr_set_active_renderer: ::core::option::Option<CtrlSrvrSetActiveRenderer>,
    #[prost(message, optional, tag = "64")]
    pub ctrl_srvr_set_volume: ::core::option::Option<CtrlSrvrSetVolume>,
    #[prost(message, optional, tag = "65")]
    pub ctrl_srvr_clear_queue: ::core::option::Option<CtrlSrvrClearQueue>,
    #[prost(message, optional, tag = "66")]
    pub ctrl_srvr_queue_load_tracks: ::core::option::Option<CtrlSrvrQueueLoadTracks>,
    #[prost(message, optional, tag = "67")]
    pub ctrl_srvr_queue_insert_tracks: ::core::option::Option<CtrlSrvrQueueInsertTracks>,
    #[prost(message, optional, tag = "68")]
    pub ctrl_srvr_queue_add_tracks: ::core::option::Option<CtrlSrvrQueueAddTracks>,
    #[prost(message, optional, tag = "69")]
    pub ctrl_srvr_queue_remove_tracks: ::core::option::Option<CtrlSrvrQueueRemoveTracks>,
    #[prost(message, optional, tag = "70")]
    pub ctrl_srvr_queue_reorder_tracks: ::core::option::Option<CtrlSrvrQueueReorderTracks>,
    #[prost(message, optional, tag = "71")]
    pub ctrl_srvr_set_shuffle_mode: ::core::option::Option<CtrlSrvrSetShuffleMode>,
    #[prost(message, optional, tag = "72")]
    pub ctrl_srvr_set_loop_mode: ::core::option::Option<CtrlSrvrSetLoopMode>,
    #[prost(message, optional, tag = "73")]
    pub ctrl_srvr_mute_volume: ::core::option::Option<CtrlSrvrMuteVolume>,
    #[prost(message, optional, tag = "74")]
    pub ctrl_srvr_set_max_audio_quality: ::core::option::Option<CtrlSrvrSetMaxAudioQuality>,
    #[prost(message, optional, tag = "75")]
    pub ctrl_srvr_set_queue_state: ::core::option::Option<CtrlSrvrSetQueueState>,
    #[prost(message, optional, tag = "76")]
    pub ctrl_srvr_ask_for_queue_state: ::core::option::Option<CtrlSrvrAskForQueueState>,
    #[prost(message, optional, tag = "77")]
    pub ctrl_srvr_ask_for_renderer_state: ::core::option::Option<CtrlSrvrAskForRendererState>,
    #[prost(message, optional, tag = "78")]
    pub ctrl_srvr_set_autoplay_mode: ::core::option::Option<CtrlSrvrSetAutoplayMode>,
    #[prost(message, optional, tag = "79")]
    pub ctrl_srvr_autoplay_load_tracks: ::core::option::Option<CtrlSrvrAutoplayLoadTracks>,
    #[prost(message, optional, tag = "80")]
    pub ctrl_srvr_autoplay_remove_tracks: ::core::option::Option<CtrlSrvrAutoplayRemoveTracks>,
    #[prost(message, optional, tag = "81")]
    pub srvr_ctrl_session_state: ::core::option::Option<SrvrCtrlSessionState>,
    #[prost(message, optional, tag = "82")]
    pub srvr_ctrl_renderer_state_updated: ::core::option::Option<SrvrCtrlRendererStateUpdated>,
    #[prost(message, optional, tag = "83")]
    pub srvr_ctrl_add_renderer: ::core::option::Option<SrvrCtrlAddRenderer>,
    #[prost(message, optional, tag = "84")]
    pub srvr_ctrl_update_renderer: ::core::option::Option<SrvrCtrlUpdateRenderer>,
    #[prost(message, optional, tag = "85")]
    pub srvr_ctrl_remove_renderer: ::core::option::Option<SrvrCtrlRemoveRenderer>,
    #[prost(message, optional, tag = "86")]
    pub srvr_ctrl_active_renderer_changed: ::core::option::Option<SrvrCtrlActiveRendererChanged>,
    #[prost(message, optional, tag = "87")]
    pub srvr_ctrl_volume_changed: ::core::option::Option<SrvrCtrlVolumeChanged>,
    #[prost(message, optional, tag = "88")]
    pub srvr_ctrl_queue_error_message: ::core::option::Option<SrvrCtrlQueueErrorMessage>,
    #[prost(message, optional, tag = "89")]
    pub srvr_ctrl_queue_cleared: ::core::option::Option<SrvrCtrlQueueCleared>,
    #[prost(message, optional, tag = "90")]
    pub srvr_ctrl_queue_state: ::core::option::Option<SrvrCtrlQueueState>,
    #[prost(message, optional, tag = "91")]
    pub srvr_ctrl_queue_tracks_loaded: ::core::option::Option<SrvrCtrlQueueTracksLoaded>,
    #[prost(message, optional, tag = "92")]
    pub srvr_ctrl_queue_tracks_inserted: ::core::option::Option<SrvrCtrlQueueTracksInserted>,
    #[prost(message, optional, tag = "93")]
    pub srvr_ctrl_queue_tracks_added: ::core::option::Option<SrvrCtrlQueueTracksAdded>,
    #[prost(message, optional, tag = "94")]
    pub srvr_ctrl_queue_tracks_removed: ::core::option::Option<SrvrCtrlQueueTracksRemoved>,
    #[prost(message, optional, tag = "95")]
    pub srvr_ctrl_queue_tracks_reordered: ::core::option::Option<SrvrCtrlQueueTracksReordered>,
    #[prost(message, optional, tag = "96")]
    pub srvr_ctrl_shuffle_mode_set: ::core::option::Option<SrvrCtrlShuffleModeSet>,
    #[prost(message, optional, tag = "97")]
    pub srvr_ctrl_loop_mode_set: ::core::option::Option<SrvrCtrlLoopModeSet>,
    #[prost(message, optional, tag = "98")]
    pub srvr_ctrl_volume_muted: ::core::option::Option<SrvrCtrlVolumeMuted>,
    #[prost(message, optional, tag = "99")]
    pub srvr_ctrl_max_audio_quality_changed: ::core::option::Option<SrvrCtrlMaxAudioQualityChanged>,
    #[prost(message, optional, tag = "100")]
    pub srvr_ctrl_file_audio_quality_changed:
        ::core::option::Option<SrvrCtrlFileAudioQualityChanged>,
    #[prost(message, optional, tag = "101")]
    pub srvr_ctrl_device_audio_quality_changed:
        ::core::option::Option<SrvrCtrlDeviceAudioQualityChanged>,
    #[prost(message, optional, tag = "102")]
    pub srvr_ctrl_autoplay_mode_set: ::core::option::Option<SrvrCtrlAutoplayModeSet>,
    #[prost(message, optional, tag = "103")]
    pub srvr_ctrl_autoplay_tracks_loaded: ::core::option::Option<SrvrCtrlAutoplayTracksLoaded>,
    #[prost(message, optional, tag = "104")]
    pub srvr_ctrl_autoplay_tracks_removed: ::core::option::Option<SrvrCtrlAutoplayTracksRemoved>,
    #[prost(message, optional, tag = "105")]
    pub srvr_ctrl_queue_tracks_added_from_autoplay:
        ::core::option::Option<SrvrCtrlQueueTracksAddedFromAutoplay>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BufferState {
    Unknown = 0,
    Buffering = 1,
    Ok = 2,
    Error = 3,
    Underrun = 4,
}
impl BufferState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "BUFFER_STATE_UNKNOWN",
            Self::Buffering => "BUFFER_STATE_BUFFERING",
            Self::Ok => "BUFFER_STATE_OK",
            Self::Error => "BUFFER_STATE_ERROR",
            Self::Underrun => "BUFFER_STATE_UNDERRUN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BUFFER_STATE_UNKNOWN" => Some(Self::Unknown),
            "BUFFER_STATE_BUFFERING" => Some(Self::Buffering),
            "BUFFER_STATE_OK" => Some(Self::Ok),
            "BUFFER_STATE_ERROR" => Some(Self::Error),
            "BUFFER_STATE_UNDERRUN" => Some(Self::Underrun),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PlayingState {
    Unknown = 0,
    Stopped = 1,
    Playing = 2,
    Paused = 3,
}
impl PlayingState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "PLAYING_STATE_UNKNOWN",
            Self::Stopped => "PLAYING_STATE_STOPPED",
            Self::Playing => "PLAYING_STATE_PLAYING",
            Self::Paused => "PLAYING_STATE_PAUSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PLAYING_STATE_UNKNOWN" => Some(Self::Unknown),
            "PLAYING_STATE_STOPPED" => Some(Self::Stopped),
            "PLAYING_STATE_PLAYING" => Some(Self::Playing),
            "PLAYING_STATE_PAUSED" => Some(Self::Paused),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LoopMode {
    Unknown = 0,
    Off = 1,
    RepeatOne = 2,
    RepeatAll = 3,
}
impl LoopMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "LOOP_MODE_UNKNOWN",
            Self::Off => "LOOP_MODE_OFF",
            Self::RepeatOne => "LOOP_MODE_REPEAT_ONE",
            Self::RepeatAll => "LOOP_MODE_REPEAT_ALL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOOP_MODE_UNKNOWN" => Some(Self::Unknown),
            "LOOP_MODE_OFF" => Some(Self::Off),
            "LOOP_MODE_REPEAT_ONE" => Some(Self::RepeatOne),
            "LOOP_MODE_REPEAT_ALL" => Some(Self::RepeatAll),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AudioQuality {
    Unknown = 0,
    Mp3 = 1,
    Cd = 2,
    HiresLevel1 = 3,
    HiresLevel2 = 4,
    HiresLevel3 = 5,
}
impl AudioQuality {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "AUDIO_QUALITY_UNKNOWN",
            Self::Mp3 => "AUDIO_QUALITY_MP3",
            Self::Cd => "AUDIO_QUALITY_CD",
            Self::HiresLevel1 => "AUDIO_QUALITY_HIRES_LEVEL1",
            Self::HiresLevel2 => "AUDIO_QUALITY_HIRES_LEVEL2",
            Self::HiresLevel3 => "AUDIO_QUALITY_HIRES_LEVEL3",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUDIO_QUALITY_UNKNOWN" => Some(Self::Unknown),
            "AUDIO_QUALITY_MP3" => Some(Self::Mp3),
            "AUDIO_QUALITY_CD" => Some(Self::Cd),
            "AUDIO_QUALITY_HIRES_LEVEL1" => Some(Self::HiresLevel1),
            "AUDIO_QUALITY_HIRES_LEVEL2" => Some(Self::HiresLevel2),
            "AUDIO_QUALITY_HIRES_LEVEL3" => Some(Self::HiresLevel3),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeviceType {
    Unknown = 0,
    Speaker = 1,
    Streamer = 2,
    Tv = 3,
    Soundbar = 4,
    Computer = 5,
    Mobile = 6,
    Cast = 7,
    Headphones = 8,
    Tablet = 9,
}
impl DeviceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "DEVICE_TYPE_UNKNOWN",
            Self::Speaker => "DEVICE_TYPE_SPEAKER",
            Self::Streamer => "DEVICE_TYPE_STREAMER",
            Self::Tv => "DEVICE_TYPE_TV",
            Self::Soundbar => "DEVICE_TYPE_SOUNDBAR",
            Self::Computer => "DEVICE_TYPE_COMPUTER",
            Self::Mobile => "DEVICE_TYPE_MOBILE",
            Self::Cast => "DEVICE_TYPE_CAST",
            Self::Headphones => "DEVICE_TYPE_HEADPHONES",
            Self::Tablet => "DEVICE_TYPE_TABLET",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEVICE_TYPE_UNKNOWN" => Some(Self::Unknown),
            "DEVICE_TYPE_SPEAKER" => Some(Self::Speaker),
            "DEVICE_TYPE_STREAMER" => Some(Self::Streamer),
            "DEVICE_TYPE_TV" => Some(Self::Tv),
            "DEVICE_TYPE_SOUNDBAR" => Some(Self::Soundbar),
            "DEVICE_TYPE_COMPUTER" => Some(Self::Computer),
            "DEVICE_TYPE_MOBILE" => Some(Self::Mobile),
            "DEVICE_TYPE_CAST" => Some(Self::Cast),
            "DEVICE_TYPE_HEADPHONES" => Some(Self::Headphones),
            "DEVICE_TYPE_TABLET" => Some(Self::Tablet),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VolumeRemoteControl {
    Unknown = 0,
    NotAllowed = 1,
    Allowed = 2,
}
impl VolumeRemoteControl {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "VOLUME_REMOTE_CONTROL_UNKNOWN",
            Self::NotAllowed => "VOLUME_REMOTE_CONTROL_NOT_ALLOWED",
            Self::Allowed => "VOLUME_REMOTE_CONTROL_ALLOWED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VOLUME_REMOTE_CONTROL_UNKNOWN" => Some(Self::Unknown),
            "VOLUME_REMOTE_CONTROL_NOT_ALLOWED" => Some(Self::NotAllowed),
            "VOLUME_REMOTE_CONTROL_ALLOWED" => Some(Self::Allowed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NetworkType {
    Unknown = 0,
    Wifi = 1,
    Cellular = 2,
}
impl NetworkType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "NETWORK_TYPE_UNKNOWN",
            Self::Wifi => "NETWORK_TYPE_WIFI",
            Self::Cellular => "NETWORK_TYPE_CELLULAR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NETWORK_TYPE_UNKNOWN" => Some(Self::Unknown),
            "NETWORK_TYPE_WIFI" => Some(Self::Wifi),
            "NETWORK_TYPE_CELLULAR" => Some(Self::Cellular),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorType {
    Unknown = 0,
    TrackNotFound = 1,
    TrackNotStreamable = 2,
    TrackMusicDataInvalid = 3,
    ServiceError = 4,
    NetworkError = 5,
    OtherErrors = 100,
}
impl ErrorType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ERROR_TYPE_UNKNOWN",
            Self::TrackNotFound => "ERROR_TYPE_TRACK_NOT_FOUND",
            Self::TrackNotStreamable => "ERROR_TYPE_TRACK_NOT_STREAMABLE",
            Self::TrackMusicDataInvalid => "ERROR_TYPE_TRACK_MUSIC_DATA_INVALID",
            Self::ServiceError => "ERROR_TYPE_SERVICE_ERROR",
            Self::NetworkError => "ERROR_TYPE_NETWORK_ERROR",
            Self::OtherErrors => "ERROR_TYPE_OTHER_ERRORS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ERROR_TYPE_UNKNOWN" => Some(Self::Unknown),
            "ERROR_TYPE_TRACK_NOT_FOUND" => Some(Self::TrackNotFound),
            "ERROR_TYPE_TRACK_NOT_STREAMABLE" => Some(Self::TrackNotStreamable),
            "ERROR_TYPE_TRACK_MUSIC_DATA_INVALID" => Some(Self::TrackMusicDataInvalid),
            "ERROR_TYPE_SERVICE_ERROR" => Some(Self::ServiceError),
            "ERROR_TYPE_NETWORK_ERROR" => Some(Self::NetworkError),
            "ERROR_TYPE_OTHER_ERRORS" => Some(Self::OtherErrors),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RendererStatus {
    Unknown = 0,
    ActiveConnected = 1,
    ActiveDisconnected = 2,
    Inactive = 3,
}
impl RendererStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "RENDERER_STATUS_UNKNOWN",
            Self::ActiveConnected => "RENDERER_STATUS_ACTIVE_CONNECTED",
            Self::ActiveDisconnected => "RENDERER_STATUS_ACTIVE_DISCONNECTED",
            Self::Inactive => "RENDERER_STATUS_INACTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RENDERER_STATUS_UNKNOWN" => Some(Self::Unknown),
            "RENDERER_STATUS_ACTIVE_CONNECTED" => Some(Self::ActiveConnected),
            "RENDERER_STATUS_ACTIVE_DISCONNECTED" => Some(Self::ActiveDisconnected),
            "RENDERER_STATUS_INACTIVE" => Some(Self::Inactive),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JoinSessionReason {
    Unknown = 0,
    ControllerRequest = 1,
    Reconnection = 2,
}
impl JoinSessionReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "JOIN_SESSION_REASON_UNKNOWN",
            Self::ControllerRequest => "JOIN_SESSION_REASON_CONTROLLER_REQUEST",
            Self::Reconnection => "JOIN_SESSION_REASON_RECONNECTION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOIN_SESSION_REASON_UNKNOWN" => Some(Self::Unknown),
            "JOIN_SESSION_REASON_CONTROLLER_REQUEST" => Some(Self::ControllerRequest),
            "JOIN_SESSION_REASON_RECONNECTION" => Some(Self::Reconnection),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ActionType {
    Unknown = 0,
    Previous = 1,
    Next = 2,
    RepeatOff = 3,
    RepeatOne = 4,
    RepeatAll = 5,
    ShuffleOff = 6,
    ShuffleOn = 7,
    Seek = 8,
}
impl ActionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ACTION_TYPE_UNKNOWN",
            Self::Previous => "ACTION_TYPE_PREVIOUS",
            Self::Next => "ACTION_TYPE_NEXT",
            Self::RepeatOff => "ACTION_TYPE_REPEAT_OFF",
            Self::RepeatOne => "ACTION_TYPE_REPEAT_ONE",
            Self::RepeatAll => "ACTION_TYPE_REPEAT_ALL",
            Self::ShuffleOff => "ACTION_TYPE_SHUFFLE_OFF",
            Self::ShuffleOn => "ACTION_TYPE_SHUFFLE_ON",
            Self::Seek => "ACTION_TYPE_SEEK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTION_TYPE_UNKNOWN" => Some(Self::Unknown),
            "ACTION_TYPE_PREVIOUS" => Some(Self::Previous),
            "ACTION_TYPE_NEXT" => Some(Self::Next),
            "ACTION_TYPE_REPEAT_OFF" => Some(Self::RepeatOff),
            "ACTION_TYPE_REPEAT_ONE" => Some(Self::RepeatOne),
            "ACTION_TYPE_REPEAT_ALL" => Some(Self::RepeatAll),
            "ACTION_TYPE_SHUFFLE_OFF" => Some(Self::ShuffleOff),
            "ACTION_TYPE_SHUFFLE_ON" => Some(Self::ShuffleOn),
            "ACTION_TYPE_SEEK" => Some(Self::Seek),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    Unknown = 0,
    Error = 1,
    PlaybackError = 2,
    Authenticate = 3,
    RndrSrvrJoinSession = 21,
    RndrSrvrDeviceInfoUpdated = 22,
    RndrSrvrStateUpdated = 23,
    RndrSrvrRendererAction = 24,
    RndrSrvrVolumeChanged = 25,
    RndrSrvrFileAudioQualityChanged = 26,
    RndrSrvrDeviceAudioQualityChanged = 27,
    RndrSrvrMaxAudioQualityChanged = 28,
    RndrSrvrVolumeMuted = 29,
    SrvrRndrSetState = 41,
    SrvrRndrSetVolume = 42,
    SrvrRndrSetActive = 43,
    SrvrRndrSetMaxAudioQuality = 44,
    SrvrRndrSetLoopMode = 45,
    SrvrRndrSetShuffleMode = 46,
    SrvrRndrMuteVolume = 47,
    CtrlSrvrJoinSession = 61,
    CtrlSrvrSetPlayerState = 62,
    CtrlSrvrSetActiveRenderer = 63,
    CtrlSrvrSetVolume = 64,
    CtrlSrvrClearQueue = 65,
    CtrlSrvrQueueLoadTracks = 66,
    CtrlSrvrQueueInsertTracks = 67,
    CtrlSrvrQueueAddTracks = 68,
    CtrlSrvrQueueRemoveTracks = 69,
    CtrlSrvrQueueReorderTracks = 70,
    CtrlSrvrSetShuffleMode = 71,
    CtrlSrvrSetLoopMode = 72,
    CtrlSrvrMuteVolume = 73,
    CtrlSrvrSetMaxAudioQuality = 74,
    CtrlSrvrSetQueueState = 75,
    CtrlSrvrAskForQueueState = 76,
    CtrlSrvrAskForRendererState = 77,
    CtrlSrvrSetAutoplayMode = 78,
    CtrlSrvrAutoplayLoadTracks = 79,
    CtrlSrvrAutoplayRemoveTracks = 80,
    SrvrCtrlSessionState = 81,
    SrvrCtrlRendererStateUpdated = 82,
    SrvrCtrlAddRenderer = 83,
    SrvrCtrlUpdateRenderer = 84,
    SrvrCtrlRemoveRenderer = 85,
    SrvrCtrlActiveRendererChanged = 86,
    SrvrCtrlVolumeChanged = 87,
    SrvrCtrlQueueErrorMessage = 88,
    SrvrCtrlQueueCleared = 89,
    SrvrCtrlQueueState = 90,
    SrvrCtrlQueueTracksLoaded = 91,
    SrvrCtrlQueueTracksInserted = 92,
    SrvrCtrlQueueTracksAdded = 93,
    SrvrCtrlQueueTracksRemoved = 94,
    SrvrCtrlQueueTracksReordered = 95,
    SrvrCtrlShuffleModeSet = 96,
    SrvrCtrlLoopModeSet = 97,
    SrvrCtrlVolumeMuted = 98,
    SrvrCtrlMaxAudioQualityChanged = 99,
    SrvrCtrlFileAudioQualityChanged = 100,
    SrvrCtrlDeviceAudioQualityChanged = 101,
    SrvrCtrlAutoplayModeSet = 102,
    SrvrCtrlAutoplayTracksLoaded = 103,
    SrvrCtrlAutoplayTracksRemoved = 104,
    SrvrCtrlQueueTracksAddedFromAutoplay = 105,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "MESSAGE_TYPE_UNKNOWN",
            Self::Error => "MESSAGE_TYPE_ERROR",
            Self::PlaybackError => "MESSAGE_TYPE_PLAYBACK_ERROR",
            Self::Authenticate => "MESSAGE_TYPE_AUTHENTICATE",
            Self::RndrSrvrJoinSession => "MESSAGE_TYPE_RNDR_SRVR_JOIN_SESSION",
            Self::RndrSrvrDeviceInfoUpdated => "MESSAGE_TYPE_RNDR_SRVR_DEVICE_INFO_UPDATED",
            Self::RndrSrvrStateUpdated => "MESSAGE_TYPE_RNDR_SRVR_STATE_UPDATED",
            Self::RndrSrvrRendererAction => "MESSAGE_TYPE_RNDR_SRVR_RENDERER_ACTION",
            Self::RndrSrvrVolumeChanged => "MESSAGE_TYPE_RNDR_SRVR_VOLUME_CHANGED",
            Self::RndrSrvrFileAudioQualityChanged => {
                "MESSAGE_TYPE_RNDR_SRVR_FILE_AUDIO_QUALITY_CHANGED"
            }
            Self::RndrSrvrDeviceAudioQualityChanged => {
                "MESSAGE_TYPE_RNDR_SRVR_DEVICE_AUDIO_QUALITY_CHANGED"
            }
            Self::RndrSrvrMaxAudioQualityChanged => {
                "MESSAGE_TYPE_RNDR_SRVR_MAX_AUDIO_QUALITY_CHANGED"
            }
            Self::RndrSrvrVolumeMuted => "MESSAGE_TYPE_RNDR_SRVR_VOLUME_MUTED",
            Self::SrvrRndrSetState => "MESSAGE_TYPE_SRVR_RNDR_SET_STATE",
            Self::SrvrRndrSetVolume => "MESSAGE_TYPE_SRVR_RNDR_SET_VOLUME",
            Self::SrvrRndrSetActive => "MESSAGE_TYPE_SRVR_RNDR_SET_ACTIVE",
            Self::SrvrRndrSetMaxAudioQuality => "MESSAGE_TYPE_SRVR_RNDR_SET_MAX_AUDIO_QUALITY",
            Self::SrvrRndrSetLoopMode => "MESSAGE_TYPE_SRVR_RNDR_SET_LOOP_MODE",
            Self::SrvrRndrSetShuffleMode => "MESSAGE_TYPE_SRVR_RNDR_SET_SHUFFLE_MODE",
            Self::SrvrRndrMuteVolume => "MESSAGE_TYPE_SRVR_RNDR_MUTE_VOLUME",
            Self::CtrlSrvrJoinSession => "MESSAGE_TYPE_CTRL_SRVR_JOIN_SESSION",
            Self::CtrlSrvrSetPlayerState => "MESSAGE_TYPE_CTRL_SRVR_SET_PLAYER_STATE",
            Self::CtrlSrvrSetActiveRenderer => "MESSAGE_TYPE_CTRL_SRVR_SET_ACTIVE_RENDERER",
            Self::CtrlSrvrSetVolume => "MESSAGE_TYPE_CTRL_SRVR_SET_VOLUME",
            Self::CtrlSrvrClearQueue => "MESSAGE_TYPE_CTRL_SRVR_CLEAR_QUEUE",
            Self::CtrlSrvrQueueLoadTracks => "MESSAGE_TYPE_CTRL_SRVR_QUEUE_LOAD_TRACKS",
            Self::CtrlSrvrQueueInsertTracks => "MESSAGE_TYPE_CTRL_SRVR_QUEUE_INSERT_TRACKS",
            Self::CtrlSrvrQueueAddTracks => "MESSAGE_TYPE_CTRL_SRVR_QUEUE_ADD_TRACKS",
            Self::CtrlSrvrQueueRemoveTracks => "MESSAGE_TYPE_CTRL_SRVR_QUEUE_REMOVE_TRACKS",
            Self::CtrlSrvrQueueReorderTracks => "MESSAGE_TYPE_CTRL_SRVR_QUEUE_REORDER_TRACKS",
            Self::CtrlSrvrSetShuffleMode => "MESSAGE_TYPE_CTRL_SRVR_SET_SHUFFLE_MODE",
            Self::CtrlSrvrSetLoopMode => "MESSAGE_TYPE_CTRL_SRVR_SET_LOOP_MODE",
            Self::CtrlSrvrMuteVolume => "MESSAGE_TYPE_CTRL_SRVR_MUTE_VOLUME",
            Self::CtrlSrvrSetMaxAudioQuality => "MESSAGE_TYPE_CTRL_SRVR_SET_MAX_AUDIO_QUALITY",
            Self::CtrlSrvrSetQueueState => "MESSAGE_TYPE_CTRL_SRVR_SET_QUEUE_STATE",
            Self::CtrlSrvrAskForQueueState => "MESSAGE_TYPE_CTRL_SRVR_ASK_FOR_QUEUE_STATE",
            Self::CtrlSrvrAskForRendererState => "MESSAGE_TYPE_CTRL_SRVR_ASK_FOR_RENDERER_STATE",
            Self::CtrlSrvrSetAutoplayMode => "MESSAGE_TYPE_CTRL_SRVR_SET_AUTOPLAY_MODE",
            Self::CtrlSrvrAutoplayLoadTracks => "MESSAGE_TYPE_CTRL_SRVR_AUTOPLAY_LOAD_TRACKS",
            Self::CtrlSrvrAutoplayRemoveTracks => "MESSAGE_TYPE_CTRL_SRVR_AUTOPLAY_REMOVE_TRACKS",
            Self::SrvrCtrlSessionState => "MESSAGE_TYPE_SRVR_CTRL_SESSION_STATE",
            Self::SrvrCtrlRendererStateUpdated => "MESSAGE_TYPE_SRVR_CTRL_RENDERER_STATE_UPDATED",
            Self::SrvrCtrlAddRenderer => "MESSAGE_TYPE_SRVR_CTRL_ADD_RENDERER",
            Self::SrvrCtrlUpdateRenderer => "MESSAGE_TYPE_SRVR_CTRL_UPDATE_RENDERER",
            Self::SrvrCtrlRemoveRenderer => "MESSAGE_TYPE_SRVR_CTRL_REMOVE_RENDERER",
            Self::SrvrCtrlActiveRendererChanged => "MESSAGE_TYPE_SRVR_CTRL_ACTIVE_RENDERER_CHANGED",
            Self::SrvrCtrlVolumeChanged => "MESSAGE_TYPE_SRVR_CTRL_VOLUME_CHANGED",
            Self::SrvrCtrlQueueErrorMessage => "MESSAGE_TYPE_SRVR_CTRL_QUEUE_ERROR_MESSAGE",
            Self::SrvrCtrlQueueCleared => "MESSAGE_TYPE_SRVR_CTRL_QUEUE_CLEARED",
            Self::SrvrCtrlQueueState => "MESSAGE_TYPE_SRVR_CTRL_QUEUE_STATE",
            Self::SrvrCtrlQueueTracksLoaded => "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_LOADED",
            Self::SrvrCtrlQueueTracksInserted => "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_INSERTED",
            Self::SrvrCtrlQueueTracksAdded => "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_ADDED",
            Self::SrvrCtrlQueueTracksRemoved => "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_REMOVED",
            Self::SrvrCtrlQueueTracksReordered => "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_REORDERED",
            Self::SrvrCtrlShuffleModeSet => "MESSAGE_TYPE_SRVR_CTRL_SHUFFLE_MODE_SET",
            Self::SrvrCtrlLoopModeSet => "MESSAGE_TYPE_SRVR_CTRL_LOOP_MODE_SET",
            Self::SrvrCtrlVolumeMuted => "MESSAGE_TYPE_SRVR_CTRL_VOLUME_MUTED",
            Self::SrvrCtrlMaxAudioQualityChanged => {
                "MESSAGE_TYPE_SRVR_CTRL_MAX_AUDIO_QUALITY_CHANGED"
            }
            Self::SrvrCtrlFileAudioQualityChanged => {
                "MESSAGE_TYPE_SRVR_CTRL_FILE_AUDIO_QUALITY_CHANGED"
            }
            Self::SrvrCtrlDeviceAudioQualityChanged => {
                "MESSAGE_TYPE_SRVR_CTRL_DEVICE_AUDIO_QUALITY_CHANGED"
            }
            Self::SrvrCtrlAutoplayModeSet => "MESSAGE_TYPE_SRVR_CTRL_AUTOPLAY_MODE_SET",
            Self::SrvrCtrlAutoplayTracksLoaded => "MESSAGE_TYPE_SRVR_CTRL_AUTOPLAY_TRACKS_LOADED",
            Self::SrvrCtrlAutoplayTracksRemoved => "MESSAGE_TYPE_SRVR_CTRL_AUTOPLAY_TRACKS_REMOVED",
            Self::SrvrCtrlQueueTracksAddedFromAutoplay => {
                "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_ADDED_FROM_AUTOPLAY"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MESSAGE_TYPE_UNKNOWN" => Some(Self::Unknown),
            "MESSAGE_TYPE_ERROR" => Some(Self::Error),
            "MESSAGE_TYPE_PLAYBACK_ERROR" => Some(Self::PlaybackError),
            "MESSAGE_TYPE_AUTHENTICATE" => Some(Self::Authenticate),
            "MESSAGE_TYPE_RNDR_SRVR_JOIN_SESSION" => Some(Self::RndrSrvrJoinSession),
            "MESSAGE_TYPE_RNDR_SRVR_DEVICE_INFO_UPDATED" => Some(Self::RndrSrvrDeviceInfoUpdated),
            "MESSAGE_TYPE_RNDR_SRVR_STATE_UPDATED" => Some(Self::RndrSrvrStateUpdated),
            "MESSAGE_TYPE_RNDR_SRVR_RENDERER_ACTION" => Some(Self::RndrSrvrRendererAction),
            "MESSAGE_TYPE_RNDR_SRVR_VOLUME_CHANGED" => Some(Self::RndrSrvrVolumeChanged),
            "MESSAGE_TYPE_RNDR_SRVR_FILE_AUDIO_QUALITY_CHANGED" => {
                Some(Self::RndrSrvrFileAudioQualityChanged)
            }
            "MESSAGE_TYPE_RNDR_SRVR_DEVICE_AUDIO_QUALITY_CHANGED" => {
                Some(Self::RndrSrvrDeviceAudioQualityChanged)
            }
            "MESSAGE_TYPE_RNDR_SRVR_MAX_AUDIO_QUALITY_CHANGED" => {
                Some(Self::RndrSrvrMaxAudioQualityChanged)
            }
            "MESSAGE_TYPE_RNDR_SRVR_VOLUME_MUTED" => Some(Self::RndrSrvrVolumeMuted),
            "MESSAGE_TYPE_SRVR_RNDR_SET_STATE" => Some(Self::SrvrRndrSetState),
            "MESSAGE_TYPE_SRVR_RNDR_SET_VOLUME" => Some(Self::SrvrRndrSetVolume),
            "MESSAGE_TYPE_SRVR_RNDR_SET_ACTIVE" => Some(Self::SrvrRndrSetActive),
            "MESSAGE_TYPE_SRVR_RNDR_SET_MAX_AUDIO_QUALITY" => {
                Some(Self::SrvrRndrSetMaxAudioQuality)
            }
            "MESSAGE_TYPE_SRVR_RNDR_SET_LOOP_MODE" => Some(Self::SrvrRndrSetLoopMode),
            "MESSAGE_TYPE_SRVR_RNDR_SET_SHUFFLE_MODE" => Some(Self::SrvrRndrSetShuffleMode),
            "MESSAGE_TYPE_SRVR_RNDR_MUTE_VOLUME" => Some(Self::SrvrRndrMuteVolume),
            "MESSAGE_TYPE_CTRL_SRVR_JOIN_SESSION" => Some(Self::CtrlSrvrJoinSession),
            "MESSAGE_TYPE_CTRL_SRVR_SET_PLAYER_STATE" => Some(Self::CtrlSrvrSetPlayerState),
            "MESSAGE_TYPE_CTRL_SRVR_SET_ACTIVE_RENDERER" => Some(Self::CtrlSrvrSetActiveRenderer),
            "MESSAGE_TYPE_CTRL_SRVR_SET_VOLUME" => Some(Self::CtrlSrvrSetVolume),
            "MESSAGE_TYPE_CTRL_SRVR_CLEAR_QUEUE" => Some(Self::CtrlSrvrClearQueue),
            "MESSAGE_TYPE_CTRL_SRVR_QUEUE_LOAD_TRACKS" => Some(Self::CtrlSrvrQueueLoadTracks),
            "MESSAGE_TYPE_CTRL_SRVR_QUEUE_INSERT_TRACKS" => Some(Self::CtrlSrvrQueueInsertTracks),
            "MESSAGE_TYPE_CTRL_SRVR_QUEUE_ADD_TRACKS" => Some(Self::CtrlSrvrQueueAddTracks),
            "MESSAGE_TYPE_CTRL_SRVR_QUEUE_REMOVE_TRACKS" => Some(Self::CtrlSrvrQueueRemoveTracks),
            "MESSAGE_TYPE_CTRL_SRVR_QUEUE_REORDER_TRACKS" => Some(Self::CtrlSrvrQueueReorderTracks),
            "MESSAGE_TYPE_CTRL_SRVR_SET_SHUFFLE_MODE" => Some(Self::CtrlSrvrSetShuffleMode),
            "MESSAGE_TYPE_CTRL_SRVR_SET_LOOP_MODE" => Some(Self::CtrlSrvrSetLoopMode),
            "MESSAGE_TYPE_CTRL_SRVR_MUTE_VOLUME" => Some(Self::CtrlSrvrMuteVolume),
            "MESSAGE_TYPE_CTRL_SRVR_SET_MAX_AUDIO_QUALITY" => {
                Some(Self::CtrlSrvrSetMaxAudioQuality)
            }
            "MESSAGE_TYPE_CTRL_SRVR_SET_QUEUE_STATE" => Some(Self::CtrlSrvrSetQueueState),
            "MESSAGE_TYPE_CTRL_SRVR_ASK_FOR_QUEUE_STATE" => Some(Self::CtrlSrvrAskForQueueState),
            "MESSAGE_TYPE_CTRL_SRVR_ASK_FOR_RENDERER_STATE" => {
                Some(Self::CtrlSrvrAskForRendererState)
            }
            "MESSAGE_TYPE_CTRL_SRVR_SET_AUTOPLAY_MODE" => Some(Self::CtrlSrvrSetAutoplayMode),
            "MESSAGE_TYPE_CTRL_SRVR_AUTOPLAY_LOAD_TRACKS" => Some(Self::CtrlSrvrAutoplayLoadTracks),
            "MESSAGE_TYPE_CTRL_SRVR_AUTOPLAY_REMOVE_TRACKS" => {
                Some(Self::CtrlSrvrAutoplayRemoveTracks)
            }
            "MESSAGE_TYPE_SRVR_CTRL_SESSION_STATE" => Some(Self::SrvrCtrlSessionState),
            "MESSAGE_TYPE_SRVR_CTRL_RENDERER_STATE_UPDATED" => {
                Some(Self::SrvrCtrlRendererStateUpdated)
            }
            "MESSAGE_TYPE_SRVR_CTRL_ADD_RENDERER" => Some(Self::SrvrCtrlAddRenderer),
            "MESSAGE_TYPE_SRVR_CTRL_UPDATE_RENDERER" => Some(Self::SrvrCtrlUpdateRenderer),
            "MESSAGE_TYPE_SRVR_CTRL_REMOVE_RENDERER" => Some(Self::SrvrCtrlRemoveRenderer),
            "MESSAGE_TYPE_SRVR_CTRL_ACTIVE_RENDERER_CHANGED" => {
                Some(Self::SrvrCtrlActiveRendererChanged)
            }
            "MESSAGE_TYPE_SRVR_CTRL_VOLUME_CHANGED" => Some(Self::SrvrCtrlVolumeChanged),
            "MESSAGE_TYPE_SRVR_CTRL_QUEUE_ERROR_MESSAGE" => Some(Self::SrvrCtrlQueueErrorMessage),
            "MESSAGE_TYPE_SRVR_CTRL_QUEUE_CLEARED" => Some(Self::SrvrCtrlQueueCleared),
            "MESSAGE_TYPE_SRVR_CTRL_QUEUE_STATE" => Some(Self::SrvrCtrlQueueState),
            "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_LOADED" => Some(Self::SrvrCtrlQueueTracksLoaded),
            "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_INSERTED" => {
                Some(Self::SrvrCtrlQueueTracksInserted)
            }
            "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_ADDED" => Some(Self::SrvrCtrlQueueTracksAdded),
            "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_REMOVED" => Some(Self::SrvrCtrlQueueTracksRemoved),
            "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_REORDERED" => {
                Some(Self::SrvrCtrlQueueTracksReordered)
            }
            "MESSAGE_TYPE_SRVR_CTRL_SHUFFLE_MODE_SET" => Some(Self::SrvrCtrlShuffleModeSet),
            "MESSAGE_TYPE_SRVR_CTRL_LOOP_MODE_SET" => Some(Self::SrvrCtrlLoopModeSet),
            "MESSAGE_TYPE_SRVR_CTRL_VOLUME_MUTED" => Some(Self::SrvrCtrlVolumeMuted),
            "MESSAGE_TYPE_SRVR_CTRL_MAX_AUDIO_QUALITY_CHANGED" => {
                Some(Self::SrvrCtrlMaxAudioQualityChanged)
            }
            "MESSAGE_TYPE_SRVR_CTRL_FILE_AUDIO_QUALITY_CHANGED" => {
                Some(Self::SrvrCtrlFileAudioQualityChanged)
            }
            "MESSAGE_TYPE_SRVR_CTRL_DEVICE_AUDIO_QUALITY_CHANGED" => {
                Some(Self::SrvrCtrlDeviceAudioQualityChanged)
            }
            "MESSAGE_TYPE_SRVR_CTRL_AUTOPLAY_MODE_SET" => Some(Self::SrvrCtrlAutoplayModeSet),
            "MESSAGE_TYPE_SRVR_CTRL_AUTOPLAY_TRACKS_LOADED" => {
                Some(Self::SrvrCtrlAutoplayTracksLoaded)
            }
            "MESSAGE_TYPE_SRVR_CTRL_AUTOPLAY_TRACKS_REMOVED" => {
                Some(Self::SrvrCtrlAutoplayTracksRemoved)
            }
            "MESSAGE_TYPE_SRVR_CTRL_QUEUE_TRACKS_ADDED_FROM_AUTOPLAY" => {
                Some(Self::SrvrCtrlQueueTracksAddedFromAutoplay)
            }
            _ => None,
        }
    }
}
